gpus: [0]
epochs: 400
learning_rate: 5e-5
pretrained_path: 'artifacts/checkpoint/last.ckpt'
seg_len: 200
overlap: 10
pin_memory: True
random_seed: 13
condition_eval: False
drop_c_con: True

train_target: 'gen_noise'

score_path: example_pieces/Bach_fugue_870.musicxml
output_path: inference_out/test.mid


test:
    sample_steps_frac: 1
    transfer: False
        
trainer:
    gpus: ${gpus}
    

defaults:
    - model: ClassifierFreeDenoiser #  DenoiserUnet or ClassifierFreeDenoiser
    - task: classifierfree_diffusion


hydra:  
  output_subdir: null  
  run:  
    dir: .